---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: arch
    image: "archlinux:latest"
    command: ${MOLECULE_PODMAN_COMMAND:-"/usr/lib/systemd/systemd"}
    systemd: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: prepare.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    # - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
