---
- name: Prepare
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Create molecule test user
      ansible.builtin.user:
        name: molecule
        comment: molecule test user
        shell: /bin/bash
        state: present
