---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  provision: no
  cachier: machine
  parallel: true
platforms:
  - name: freebsd
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
    box: ${MOLECULE_BOX:-generic/freebsd13}
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ${MOLECULE_VERIFY:-verify.yml}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    # - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
