---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# Ref: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
#

name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'wesmarcum.sudo'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo.
        uses: actions/checkout@v3
        with:
          path: 'wesmarcum.sudo'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new Galaxy import.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
